### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by jonlay** [wearehanno/playbook#1]
Temporarily using the following images:

![xero1](https://cloud.githubusercontent.com/assets/1898889/7507931/5faaddf6-f4aa-11e4-8eea-6eb76337b94e.png)

![xero2](https://cloud.githubusercontent.com/assets/1898889/7507979/05c3cad6-f4ab-11e4-8348-2a33435dc963.png)

![xero3](https://cloud.githubusercontent.com/assets/1898889/7508000/4ad6a2ec-f4ab-11e4-939e-4536fe37faab.png)

![xero4](https://cloud.githubusercontent.com/assets/1898889/7508125/2a4e313c-f4ad-11e4-88b8-a42a72afe5f5.png)

![xero5](https://cloud.githubusercontent.com/assets/1898889/7508333/5663046a-f4b1-11e4-85ad-f793997ee380.png)

![xero6](https://cloud.githubusercontent.com/assets/1898889/7508346/8028d252-f4b1-11e4-85aa-abb392a378d6.png)

![xero7](https://cloud.githubusercontent.com/assets/1898889/7508370/ae01d4e4-f4b1-11e4-80e2-9bb8ad5b5902.png)

![xero8](https://cloud.githubusercontent.com/assets/1898889/7508394/0bbb6276-f4b2-11e4-92b2-709d4b319057.png)

![xero9](https://cloud.githubusercontent.com/assets/1898889/7508408/4a49ebac-f4b2-11e4-8ac9-2b01ab7ccc66.png)

![xero10](https://cloud.githubusercontent.com/assets/1898889/7508488/ce35d20e-f4b3-11e4-8a6b-0836177de236.png)

![xero11](https://cloud.githubusercontent.com/assets/1898889/7508595/7fbea4e6-f4b5-11e4-8dd8-41831e138354.png)

![xero12](https://cloud.githubusercontent.com/assets/1898889/7508618/e6a7b896-f4b5-11e4-921e-854c91c092b0.png)

![xero13](https://cloud.githubusercontent.com/assets/1898889/7508761/ac06ca8a-f4b8-11e4-8455-c36db0017e5f.png)

![xero14](https://cloud.githubusercontent.com/assets/1898889/7508873/da4380c6-f4ba-11e4-842e-62a3e381ae6a.png)

![xero15](https://cloud.githubusercontent.com/assets/1898889/7508874/da457e6c-f4ba-11e4-9b61-14f36945155e.png)

**Comment by marcelkalveram** [comment]
![screenshot 2015-06-18 17 52 22](https://cloud.githubusercontent.com/assets/461160/8235786/403978b4-15e4-11e5-840c-ca2b5a4c5b1c.png)

**Comment by marcelkalveram** [comment]
![screenshot 2015-06-18 18 04 55](https://cloud.githubusercontent.com/assets/461160/8235822/8ed43c8e-15e4-11e5-8027-c4b755c78d77.png)

**Comment by marcelkalveram** [comment]
![ce-ocv7wmaaxsh_](https://cloud.githubusercontent.com/assets/461160/8236909/ffdc69d6-15eb-11e5-8b9a-e698caaea86a.png)

**Comment by jonlay** [comment]
![2015-10-21 10 23 21 am](https://cloud.githubusercontent.com/assets/1898889/10632907/206d4a4e-77df-11e5-9644-4429e21a3580.png)

**Comment by jonlay** [comment]
![contactually](https://cloud.githubusercontent.com/assets/1898889/15279322/a4393e9a-1b55-11e6-88b1-750ec261664c.png)

**Comment by jonlay** [comment]
![transferwise](https://cloud.githubusercontent.com/assets/1898889/15571124/cae13624-236b-11e6-98b5-4321c89892ca.png)

**Comment by jonlay** [comment]
![transferwise2](https://cloud.githubusercontent.com/assets/1898889/15571204/1e96dec2-236c-11e6-955a-43487ba80f26.png)

**Comment by jonlay** [comment]
![receiptbank](https://cloud.githubusercontent.com/assets/1898889/15571416/24e50514-236d-11e6-8210-e5aefc3987f1.png)

**Comment by jonlay** [comment]
![emailin](https://cloud.githubusercontent.com/assets/1898889/15571520/ca2275fc-236d-11e6-92d3-a63e95dd0a63.png)
